export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
export const PRODUCTS_RECEIVING_ERROR = 'PRODUCTS_RECEIVING_ERROR';
export const PRODUCT_WAS_REMOVED = 'PRODUCT_WAS_REMOVED';
export const PRODUCT_REMOVE_PROCESS_FAILED = 'PRODUCT_REMOVE_PROCESS_FAILED';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const PRODUCT_WAS_UPDATED = 'PRODUCT_WAS_UPDATED';
export const PRODUCT_WAS_ADDED = 'PRODUCT_WAS_ADDED';

export const PRODUCTS_PER_PAGE = 6;