export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
export const PRODUCT_WAS_REMOVED = 'PRODUCT_WAS_REMOVED';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const PRODUCT_WAS_UPDATED = 'PRODUCT_WAS_UPDATED';
export const PRODUCT_WAS_ADDED = 'PRODUCT_WAS_ADDED';
export const PRODUCT_RECEIVED = 'PRODUCT_WAS_RECEIVED';

export const PRODUCTS_PER_PAGE = 6;